name: Build WinForms App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build WinForms project
        run: msbuild ./cis2225_vetRegistration_cmoreland/vetRegistration/WindowsFormsApp1/cis2225_vetRegistration_cmoreland.csproj /p:Configuration=Release

      # <-- Upload the EXE artifact AFTER the build
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: VetRegistrationApp
          path: ./cis2225_vetRegistration_cmoreland/vetRegistration/WindowsFormsApp1/bin/Release/WindowsFormsApp1.exe
